### ISSUE TITLE
please add null safety to metrix_plugin flutter

### ISSUE THREAD

**Issue by mahdimoaz** [metrixorg/MetrixPlugins#1]

**Comment by mzmatin** [comment]
Could you please provide a description for the issue you are facing?

**Comment by mzmatin** [comment]
Could you please provide a description for the issue you are facing with?

**Comment by mahdimoaz** [comment]
My project was written with Flutter 2.2.3 and sdk: '>=2.12.0 <3.0.0'
sdk version 2.12.0 and before do not support null safety

**why did you implement git ignore on all files?**

چرا git ignore کردی همه فایل ها را؟
@mzmatin

**Comment by mzmatin** [comment]
The code has been moved to another repo. This repository is kept for issues and possible references.

Thank you for the request. We will consider is in out future releases.

**Comment by mzmatin** [comment]
The code has been moved to another repo. This repository is kept for issues and possible references.

Thank you for the request. We will consider is in out future releases.

**Comment by mzmatin** [comment]
Null safety is added in v1.1.6
